# Generated by Django 2.0.2 on 2018-04-20 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('num_guests', models.PositiveIntegerField(default=0, verbose_name='Guests')),
                ('start_date_time', models.DateTimeField(verbose_name='Start')),
                ('end_date_time', models.DateTimeField(verbose_name='End')),
                ('special_request', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(unique=True)),
                ('capacity', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.Table'),
        ),
    ]
