# Generated by Django 2.0.2 on 2018-03-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('supplier', models.CharField(max_length=200)),
                ('article_number', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('PCS', 'Pieces'), ('LTR', 'Liter')], default='KG', max_length=200)),
                ('container_amount', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minimum_quantity', models.IntegerField(default=0)),
                ('current_stock', models.IntegerField(default=0)),
                ('order_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
