# Generated by Django 2.0.2 on 2018-03-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20180322_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='stock_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
