# Generated by Django 2.0.2 on 2018-03-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20180322_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='minimum_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='order_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
