# Generated by Django 2.0.2 on 2018-03-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20180322_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='order_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
