# Generated by Django 2.0.2 on 2018-03-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20180327_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='article_number',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='container_amount',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='minimum_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='order_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='stock_value',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='unit_price',
        ),
    ]
