# Generated by Django 2.0.2 on 2018-03-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_inventory_stock_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_value',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5),
        ),
    ]
