# Generated by Django 2.0.2 on 2018-03-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20180328_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Supplier Name')),
                ('address_line1', models.CharField(max_length=200, verbose_name='Address Line')),
                ('address_line2', models.CharField(max_length=200, verbose_name='Address Line')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('email_address', models.CharField(blank=True, max_length=100, verbose_name='Email Address')),
            ],
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory'},
        ),
    ]
