# Generated by Django 2.0.2 on 2018-03-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20180322_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
