# Generated by Django 2.0.2 on 2018-03-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20180328_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('menu_items', models.ManyToManyField(to='restaurant.MenuItem')),
            ],
        ),
    ]
