# Generated by Django 2.0.2 on 2018-03-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20180322_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='stock_value',
        ),
    ]
