# Generated by Django 2.0.2 on 2018-03-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_items',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
