# Generated by Django 2.0.2 on 2018-04-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_remove_inventory_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
