# Generated by Django 2.0.2 on 2018-04-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_auto_20180404_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='_stock_value',
            field=models.DecimalField(db_column='stock_value', decimal_places=2, default=0, max_digits=5),
        ),
    ]
