# Generated by Django 2.0.2 on 2018-04-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_inventory__stock_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='_stock_value',
            field=models.DecimalField(db_column='stock_value', decimal_places=2, max_digits=5),
        ),
    ]
