# Generated by Django 2.0.2 on 2018-04-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_remove_inventory__stock_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='uplift',
            field=models.DecimalField(decimal_places=2, default=1.65, max_digits=4),
        ),
    ]
