# Generated by Django 2.0.2 on 2018-04-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_menuitem_uplift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='uplift',
        ),
    ]
