# Generated by Django 2.0.2 on 2018-04-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0025_remove_menuitem_uplift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuaddition',
            options={'verbose_name': 'Menu & Suggested selling price', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='menuitemaddition',
            options={'verbose_name': 'Menu Item & Suggested selling price', 'verbose_name_plural': 'Menu items'},
        ),
    ]
