# Generated by Django 2.0.2 on 2018-04-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_auto_20180409_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuaddition',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='menuitemaddition',
            options={'verbose_name': 'Menu item', 'verbose_name_plural': 'Menu items'},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('MG', 'Milligram'), ('G', 'Gram'), ('KG', 'Kilogram'), ('ML', 'Milliliter'), ('L', 'Liter'), ('PCS', 'Pieces')], default='G', max_length=200),
        ),
    ]
