# Generated by Django 2.0.2 on 2018-04-10 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0027_auto_20180410_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('completed', models.BooleanField(default=False)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant.MenuItem')),
            ],
        ),
        migrations.AlterModelOptions(
            name='menuitemaddition',
            options={'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu items'},
        ),
    ]
