# Generated by Django 2.0.2 on 2018-04-17 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0028_auto_20180410_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='remarks',
            field=models.CharField(default='', max_length=254, verbose_name='Remarks'),
            preserve_default=False,
        ),
    ]
