# Generated by Django 2.0.2 on 2018-04-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0029_auto_20180417_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed_time',
            field=models.DateTimeField(null=True),
        ),
    ]
