# Generated by Django 2.0.2 on 2018-04-20 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0031_auto_20180420_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 20, 16, 51, 8, 590211)),
        ),
    ]
